### ISSUE TITLE
[Bug] Banner ads are shown when "Remove ads" is enabled.

### ISSUE THREAD

**Issue by RuneCE** [YTLitePlus/YTLitePlus#180] opened 2024-06-11 17:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 16.3.1
- Device model: iPad Pro (11-inch) - 1st gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.22.6-4.0.1

### Describe the bug

When having "Remove ads" enabled, as shown here:
![24E4309F-392F-4735-A436-2A9ECF0DD2EE](https://github.com/YTLitePlus/YTLitePlus/assets/151409305/8a9f14a0-2a6a-43cf-8e7c-3d8575c7b707)

You will still banner advertisements on the home page, such as this one: 
![3F715B30-21F9-42A4-AE43-E960D78CC17F](https://github.com/YTLitePlus/YTLitePlus/assets/151409305/7c3a18ba-0d19-467e-bec7-dc995587d5e4)

### Steps to reproduce the issue

1. Make sure "Remove ads" is enabled in feed (it is by default)
2. Go to the YouTube Home Screen.
3. Either you will see an ad or you have to refresh the page (put your finger on screen and pull it down) to get an ad. 

### Crash log (if the app crashes)

```shell
N/A
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

N/A

**Comment by Balackburn** [comment] 2024-06-15 17:02
Sorry I can't reproduce unfortunatly?

**Comment by RuneCE** [comment] 2024-06-16 20:14
> Sorry I can't reproduce unfortunatly?

Was likely patched with newer updates, but at the time it was an issue for me and others (indicated by the 👍+2)

**Comment by axpmonkey** [comment] 2024-07-08 01:04
Still seeing the same thing.  Happens randomly.  Close and re-open the app and it works fine.  Then will randomly display banner ads again.  Seems to be happening after the app is left often for a period of time.

**Comment by RuneCE** [comment] 2024-07-08 05:09
> Still seeing the same thing. Happens randomly. Close and re-open the app and it works fine. Then will randomly display banner ads again. Seems to be happening after the app is left often for a period of time.

Yeah, it went away for a few days, then decided to return on newer releases, really unfortunate this hasn't been fixed yet.

**Comment by RuneCE** [comment] 2024-07-08 05:10
Haha even the reactions jumped from 2 to 5, more and more are experiencing the issue.
CC: @Balackburn see if you can reproduce it now. :>

**Comment by bhackel** [comment] 2024-07-22 17:10
Is this iPad only, or are people experiencing it on iPhone as well?

**Comment by RuneCE** [comment] 2024-07-22 17:48
> Is this iPad only, or are people experiencing it on iPhone as well?

Yes, unfortunately this can occur on iPhones really occasionally.

**Comment by sdburrows** [comment] 2024-07-22 21:14
I can reproduce this bug almost consistently. Simply search for 'iPad Pro 2024" scroll down and there will be an ad banner selling ipad. Not sure if this is location based. 

![20240722_211233000_iOS](https://github.com/user-attachments/assets/dfa6f92e-8c47-499f-83e0-aed46bdf36ff)

**Comment by mattmg-sys** [comment] 2024-07-23 14:03
I had this issue as well.

Try disable the following in the A/B section (youtube settings) or just paste this:

YTColdConfig.iosEnableCdtrForBanner: 0
YTColdConfig.iosEnableCdtrForSmartDownloadsOptInBa nner: 0
YTColdConfig.shoppingClientConfiglosEnableDisplaying
NewImmersiveBanner: 0
YTHotConfig.adsClientAndRenderingInfraClientGloballm plementCompletionBlockOnInfraSupportHandler:O
YTHotConfig.enableAdSpecificDismissalinShorts:0
YTHotConfig.enableldfaDirectSendingAds: 0
YTHotConfig.enablePrepareAdsOverlayForOnlineWatchE ndpointsOnly: 0
YTHotConfig.enableShortsAdsUnderlay: 0


I don’t know exactly which one of these is the culprit. But it should work.

**Comment by Yougonnayeet** [comment] 2024-08-07 20:30
Will that fix the banner ads and the server side ads?

**Comment by bhackel** [comment] 2024-09-01 10:50
Likely fixed in v5, please re-open if still having issues

**Closed by bhackel** 2024-09-01 10:50 UTC
Labels: bug, YTLite

**Comment by RuneCE** [comment] 2024-09-01 11:02
Awesome, when is V5 releasing?

**Comment by bhackel** [comment] 2024-09-01 11:46
Hey, you can build with latest commits now and it will create an iPA with v5, but there are a few maintenance things for us to do (removing duplicate tweaks) before the release will be made
