### ISSUE TITLE
[Bug] Foreground Playback Shows as Background Playback

### ISSUE THREAD

**Issue by MuhannadYT** [YTLitePlus/YTLitePlus#294] opened 2024-08-02 14:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

IOS 17.5.1

### Device model

iPhone 15

### Sideload method

self sign

### Tweak version

YTLitePlus v19.29.1-4.0.1

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When playing videos in the foreground the iPhone shows it as if it's playing in the background
The issue can be fixed by disabling "Background playback < player < YT plus-settings" but that prevents pip and background playback (in the name)

here is a video showing it
https://github.com/user-attachments/assets/1b39b110-0e37-495c-829f-e39c5fc23579

### Steps to reproduce the issue

1. Open a video in the foreground
2. you can see the video playing in the dynamic island or music control section

**Comment by bhackel** [comment] 2024-08-02 23:27
Duplicate of #215

**Closed by bhackel** 2024-08-02 23:27 UTC
Labels: bug
