### ISSUE TITLE
[Bug] Community Images/Posts don’t open on full screen

### ISSUE THREAD

**Issue by CiroHoodLove** [YTLitePlus/YTLitePlus#385] opened 2024-08-28 14:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 11

### Sideload method

Esign (Public Cert)

### Tweak version

YTLitePlus 19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

https://github.com/user-attachments/assets/51236840-5cb5-47e7-a3a9-4eb60bcb3186

### Steps to reproduce the issue

1. Click on an image (the attached video explains the issue , it’s been an issue for a while for me now)

**Comment by bhackel** [comment] 2024-08-28 15:33
Duplicate of #265, no known fix at the moment unfortunately

**Closed by bhackel** 2024-08-28 15:33 UTC
Labels: bug
