### ISSUE TITLE
[Request] Add Player Gesture controls: Volume, Seek

### ISSUE THREAD

**Issue by Auronent** [YTLitePlus/YTLitePlus#273] opened 2024-07-26 05:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

uYou has a video player feature that can adjust the volume or seek when moving your finger from left to right. Divided with three parts as shown in the photo attached, different features could be assigned to each part. This is the only feature I miss with uYou while I think everything is better in YTLitePlus. Could you please add this?

### Additional context

<img width="675" alt="Screenshot 2024-07-26 at 2 24 49 PM" src="https://github.com/user-attachments/assets/fd2a93b3-bffd-4bc2-abda-92fd378042e5">

**Comment by KieranBLK** [comment] 2024-07-26 06:23
100% agree with you here. This is such a dealbreaker.

**Comment by eliliam** [comment] 2024-07-26 20:54
Dang yeah I just changed over from uYouPlus to YTLitePlus as I was having major issues in uYouPlus, but after I configured YTLitePlus to my liking and opened up a video, I found that there's no way to change the volume via a swipe gesture in video like you can in uYouPlus. Given how much audio volume varies between videos, this was probably one of the most used features of mine, and seeing it absent from YTLitePlus is making me second guess my choice moving over to it. 

Does anyone know if there is a technical reason to not support this feature? It seems like such a vital feature after you get used to it, one I'd very much love to see added to this app!

**Comment by bhackel** [comment] 2024-07-27 05:33
Yes I am open to adding it when I have free time

**Comment by eliliam** [comment] 2024-07-27 05:36
@bhackel fantastic, that's great to hear!

**Comment by KieranBLK** [comment] 2024-07-27 06:31
> Yes I am open to adding it when I have free time

Lovely. Hopefully not just Volume though. Seeking and Brightness as well. Preferably the same implementation as uYou.

**Comment by bhackel** [comment] 2024-07-27 06:45
Duplicate of #238, please follow that post for future updates on these features

**Closed by bhackel** 2024-07-27 06:45 UTC
Labels: enhancement
