### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by Metercedes** [YTLitePlus/YTLitePlus#362] opened 2024-08-20 21:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 14 Pro Max

### Sideload method

eSign

### Tweak version

YTLitePlus_19.33.2_4.0.1

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I just installed the YTLite Plus on the default settings. It crashes whenever I try to open YT Shorts.

### Steps to reproduce the issue

1. I think I don't need to explain how to open a YT Shorts video?
2. -
3. -

### Crash log (if the app crashes)

```shell
-
```

### Additional context

-

**Comment by bhackel** [comment] 2024-08-20 21:33
This is an issue with the current version of YTLite/YouTube Plus, that will be fixed in version 5. Until then, you can either downgrade to a previous release or build the latest using 19.29.2

Duplicate of #337

**Closed by bhackel** 2024-08-20 21:33 UTC
Labels: bug
