### ISSUE TITLE
[Bug] can't watch videos in 4k60

### ISSUE THREAD

**Issue by ComfortableMilk4454** [YTLitePlus/YTLitePlus#219] opened 2024-07-08 01:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 17.5.1 (21F90)
- Device model: iPhone 13 mini
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 4.0.1

### Describe the bug

[can't watch videos in 4k60](https://youtu.be/A-sw5j7RnE0)

### Steps to reproduce the issue

1. watch vid (one i used in screen recording is https://youtu.be/N2UPds7mgWk.
2. set quality to 2160p60

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment] 2024-07-08 07:40
Duplicate of #205, please refer to that post for future updates. They have a workaround there too

**Closed** 2024-07-08 10:27 UTC
Labels: bug
