### ISSUE TITLE
[Request] Swipe gesture during video playback to adjust volume

### ISSUE THREAD

**Issue by emiliowu** [YTLitePlus/YTLitePlus#276] opened 2024-07-27 00:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Would it be possible to add a swipe gesture to adjust volume during video playback?

**Comment by bhackel** [comment] 2024-07-27 06:46
Duplicate of #238, please follow that post for future updates on these features

**Closed by bhackel** 2024-07-27 06:46 UTC
Labels: enhancement
