### ISSUE TITLE
[Bug] App Crash

### ISSUE THREAD

**Issue by Gliddq** [YTLitePlus/YTLitePlus#234] opened 2024-07-10 18:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS 17.4.1
- Device model 13
- Sideload tool E Sign
- 19.25.3-4.0.1

### Describe the bug

On the shorts tab there is a button above the like that crashes the app
![IMG_1003](https://github.com/YTLitePlus/YTLitePlus/assets/152733102/0c177d71-f22e-4e30-9438-308192761f53)

### Steps to reproduce the issue

Clicking the button

### Crash log (if the app crashes)

```shell
It won’t let me upload it :(
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by FrankTheTank07** [comment] 2024-07-10 22:36
I had the same issue. I went into the settings and disabled YouPiP and restarted the app. It fixed it for me.

**Comment by mohkg1017** [comment] 2024-07-16 17:40
anyway to remove that button?

**Comment by bhackel** [comment] 2024-07-18 05:03
Duplicate of #212, please follow there for updates

**Closed by bhackel** 2024-07-18 05:03 UTC
Labels: bug
