### ISSUE TITLE
[Bug] Home tab not loading videos

### ISSUE THREAD

**Issue by mynametoad** [YTLitePlus/YTLitePlus#348] opened 2024-08-17 06:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1 Beta 2

### Device model

iPhone 15 Pro Max

### Sideload method

Signulous

### Tweak version

YTLitePlus - v19.32.6 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When opening youtube, the home tab is completely blank

### Steps to reproduce the issue

1. open youtube
2. go to home tab
3. observe you will see loading indicators briefly but the home tab never shows videos

note: this build worked fine 8/13 until today when this issue started to occur. Restarting app and phone does not resolve

**Comment by lockieluke** [comment] 2024-08-17 10:54
Workaround: You Tab > Settings > YTLitePlus > Miscellaneous > Turn on Version Spoofer located at the bottom

Set version to v18.49.3 (Last v18 version)

Catch: you'll lose access your YouTube Playables(the mini games)

**Comment by bhackel** [comment] 2024-08-17 16:44
Can you attach screenshot? Is it completely blank or can you scroll it still? Have you tried reinstalling, maybe you have a new layout that is not supported?

**Comment by eliliam** [comment] 2024-08-17 17:23
@bhackel I am having the same issue(which @lockieluke's fix worked for), but it's scrollable, however only shorts show up. 
Video: https://files.catbox.moe/hwqife.mp4

**Comment by mynametoad** [comment] 2024-08-17 18:53
I block shorts so mine is just black and scrollable.

**Comment by mynametoad** [comment] 2024-08-17 19:07
@bhackel the workaround listed resolved it, and so did a reinstall as you suggested (spoofing not reenabled).

**Comment by bhackel** [comment] 2024-08-17 20:19
May be a duplicate of #231

**Comment by mynametoad** [comment] 2024-08-17 21:03
Opening a video did not work for getting home tab to load for me so not sure @bhackel

**Comment by bhackel** [comment] 2024-09-01 10:49
Likely fixed in v5, please re-open if you are still having this issue

**Closed by bhackel** 2024-09-01 10:49 UTC
Labels: bug, YTLite

**Comment by mynametoad** [comment] 2024-09-01 11:31
@bhackel this issue is still occurring in 5.0 but the options for blocking in feed are split out which allowed me to identify what causes this. it is specifically remove "more topics" that causes it. if i enable in 5.0, nothing loads. disable, home tab loads.

**Comment by mynametoad** [comment] 2024-09-01 20:23
i submitted this bug on the ytlite github since it is occurring in 5.0 and was finally able to identify exact cause @bhackel

**Comment by bhackel** [comment] 2024-09-01 21:33
Nice that is good to hear
