### ISSUE TITLE
[Bug] Ads occasionally shown before video

### ISSUE THREAD

**Issue by backstab5983** [YTLitePlus/YTLitePlus#181] opened 2024-06-11 19:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.23.3-4.0.1

### Describe the bug

It happened twice in two days, so not on every video, though I've never had this before happening using YTLitePlus.

A couple of times, before watching a video I got normal YT ads, check screenshots below.

### Steps to reproduce the issue

1. Check settings
![2024-06-11 22 18 22](https://github.com/YTLitePlus/YTLitePlus/assets/21013752/41a54c60-611b-477f-a817-9b801a0c91d2)
2. Open Video
3. Get ads
![2024-06-11 22 18 32](https://github.com/YTLitePlus/YTLitePlus/assets/21013752/ac97503a-3397-4cc9-902c-b261c2c7db8b)
![2024-06-11 22 18 29](https://github.com/YTLitePlus/YTLitePlus/assets/21013752/c991f280-cad9-4d15-9557-01ad177b22d1)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by a-plastic-bag** [comment] 2024-06-12 09:18
Same issue here on my iPad 6th Gen with iOS 15.4 (installed w/ TrollStore). Also seeing the sponsored banner ads at the top of the homepage.

**Comment by hobgoblin123** [comment] 2024-06-13 11:35
Wondering if this is due to the server side injection of ads from YouTube? I faced the same issue as well on my app. No ads yet on my PC (UblockOrgin + Chrome).

**Comment by Balackburn** [comment] 2024-06-15 09:32
Strange can't reproduce myself

**Comment by Skawtnyc** [comment] 2024-06-16 00:23
> Strange can't reproduce myself

I’m not experiencing any embedded ads, but I am occasionally seeing the banner ads at the top of the Home playlist.

**Comment by olivertzeng** [comment] 2024-06-16 08:58
> Strange can't reproduce myself

I started getting ads as well
Wether it's jailbroken iOS with YouTube from App Store + YTLite tweak or this
![image](https://github.com/YTLitePlus/YTLitePlus/assets/86348833/b95ee451-63ae-40fd-b9ec-4acc7a54f7cf)

**Comment by Balackburn** [comment] 2024-06-16 09:07
> > Strange can't reproduce myself
> 
> I started getting ads as well
> Wether it's jailbroken iOS with YouTube from App Store + YTLite tweak or this
> ![image](https://github.com/YTLitePlus/YTLitePlus/assets/86348833/b95ee451-63ae-40fd-b9ec-4acc7a54f7cf)

Please open an issue on the dayanch96 YTLite GitHub

**Comment by olivertzeng** [comment] 2024-06-16 09:09
I meant that this still doesn’t block the ads as well

**Comment by WilliamLeaver** [comment] 2024-06-16 19:21
Also have this issue. iPhone 12 Pro Max 17.5.1 IOS 4.0 YT lite plus. My theory is that its the new ad injection T_T

**Comment by Balackburn** [comment] 2024-06-16 21:41
> Wondering if this is due to the server side injection of ads from YouTube? I faced the same issue as well on my app. No ads yet on my PC (UblockOrgin + Chrome). 

I doubt it but maybe

**Comment by Skawtnyc** [comment] 2024-06-18 01:17
> I doubt it but maybe

From what I’ve discovered through testing is that Google has started implementing these changes within the last few versions. I’ve gone back to 19.21.3. So far it seems to have dealt with the injection and banner issues.

**Comment by Skawtnyc** [comment] 2024-06-22 20:18
Update: I’m occasionally getting injected pre-roll ads in videos, usually on channels that are high traffic money makers.

**Comment by Auxority** [comment] 2024-08-05 15:26
![image](https://github.com/user-attachments/assets/820fde2a-7328-4f20-a651-a092f87ae081)
Welp, ran into the same issue today.

**Comment by Yougonnayeet** [comment] 2024-08-07 20:35
So has anyone figured it out of how to fix this server side ads?

**Comment by Yougonnayeet** [comment] 2024-08-07 20:35
![IMG_7439](https://github.com/user-attachments/assets/d8d1e140-ef08-4261-b700-07cac6543500)

**Comment by alany08** [comment] 2024-08-09 19:17
I just got this, let me know if there is any fix

**Comment by TheKivster** [comment] 2024-08-11 21:12
This happened to me too. It seems to be random when an ad shows up.

**Comment by Diegomcha** [comment] 2024-08-17 19:48
There is an issue in YTLite traking this problem: https://github.com/dayanch96/YTLite/issues/125

**Comment by bhackel** [comment] 2024-09-01 10:50
Should be fixed in v5 now

**Closed by bhackel** 2024-09-01 10:50 UTC
Labels: bug, YTLite
